###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

# Release Details
DATE = "2022-10-26"
RELEASE = "IBM FileNet Content Manager 5.5.9-IF001"

# Repository Details
VERSION = "5.5.9-IF0014"
APP_VERSION = "22.0.1"

# OLM Version Details
CHANNEL = "v22.1"
CSV = "v55.9.1"
