###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

# Release Details
DATE = "2026-03-25"
RELEASE = "IBM FileNet Content Manager 5.5.12-IF007"

# Repository Details
VERSION = "5.5.12-IF007"
APP_VERSION = "23.0.2"

# OLM Version Details
CHANNEL = "v23.2"
CSV = "v55.12.7"

# Airgap Details
CASE_VERSION = "1.8.9"
CASE_NAME = "ibm-cp-fncm-case"