###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

# Release Details
DATE = "2023-07-26"
RELEASE = "IBM FileNet Content Manager 5.5.10-IF002"

# Repository Details
VERSION = "5.5.10-IF2"
APP_VERSION = "22.0.2"

# OLM Version Details
CHANNEL = "v22.2"
CSV = "v55.10.2"
