################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2023. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fncm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-fncm-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-fncm-catalog@sha256:28f12ca0f3069dfbd4389bc9d1f75b2a4c6ffd45c0c058ec334e1d7e5bc6b6f1
