################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2023. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fncm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-fncm-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-fncm-catalog@sha256:44ebd8f0fdaff39b41f637d53a020f6ebc5708e044b924e268dc2226bf9fc679
  updateStrategy:
    registryPoll:
      interval: 45m
