###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

# ####################################################
# ##            Registry Authentication             ##
# ####################################################

# Key used to authenticate with IBM Entitlement Registry
# Check the link on how to obtain an IBM Entitlement key https://www.ibm.com/docs/SSNW2F_5.7.0/com.ibm.dba.install/op_topics/tsk_images_enterp_entitled.html
ENTITLEMENT_KEY = "<IBMEntitlementKey>"

# CNCF Only: Pull images from a pirvate registry
# OCP deployment, use Airgap deployment method
PRIVATE_REGISTRY_HOST = "<RegistryHost>"

PRIVATE_REGISTRY_PORT = 5000

PRIVATE_REGISTRY_USERNAME = "<RegistryUser>"

PRIVATE_REGISTRY_PASSWORD = "<RegistryPassword>"

# Is your private registry using SSL - Valid values: [true; false]
PRIVATE_REGISTRY_SSL_ENABLED = true

# File Path to the ssl cert of the private registry
# Required Field only if PRIVATE_REGISTRY_SSL_ENABLED is true
# Cerificates needs to in PEM format
PRIVATE_REGISTRY_SSL_CRT_PATH = "/path/to/crt/certificate.pem"

# ####################################################
# ##          Airgap Mirroring Info                 ##
# ####################################################

# ####################################################
# ##     Filenet Content Manager Version            ##
# ####################################################
# Filenet Content Manager CASE Package version - Valid values: [1; 2; 3; 4; 5, 6]
# The latest CASE Package for that version will be pulled
# 1. 5.5.9
# 2. 5.5.10
# 3. 5.5.11
# 4. 5.5.12
# 5. 5.6.0
# 6. 5.7.0
FNCM_VERSION = 6

# ####################################################
# ##       Airgap Channel Mirror Configuration      ##
# ####################################################
# By default, each CASE Package includes all image of every FNCM Standalone version.
# Reducing the number of channels will reduce the size of the total image set.
# If set to true, the script will mirror all channels.
# If set to false, the script will mirror only the channel corresponding to the FNCM_VERSION.
# Do you want to mirror all channels - Valid values: [true; false]
MIRROR_ALL_CHANNELS = false
