###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fncmclusters.fncm.ibm.com
  labels:
    app.kubernetes.io/instance: ibm-fncm
    app.kubernetes.io/managed-by: ibm-fncm
    app.kubernetes.io/name: ibm-fncm
    release: 5.5.8
spec:
  group: fncm.ibm.com
  names:
    kind: FNCMCluster
    listKind: FNCMClusterList
    plural: fncmclusters
    singular: fncmcluster
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: FNCMCluster is the Schema for the fncmclusters API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: FNCMSpec defined the desired state of FNCM
              required:
                - appVersion
              x-kubernetes-preserve-unknown-fields: true
              properties:
                shared_configuration:
                  description: Shared Configuration for FNCM
                  required:
                    - sc_deployment_context
                    - sc_deployment_platform
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                  properties:
                    sc_deployment_fncm_license:
                      type: string
                      nullable: true
                    sc_deployment_baw_license:
                      type: string
                      nullable: true
                    sc_deployment_license:
                      type: string
                      nullable: true
                    sc_deployment_platform:
                      type: string
                    external_tls_certificate_secret:
                      type: string
                      nullable: true
                    root_ca_secret:
                      type: string
                      nullable: true
                    sc_ingress_enable:
                      type: boolean
                    sc_ingress_tls_secret_name:
                      type: string
                      nullable: true
                    trusted_certificate_list:
                      items:
                        type: string
                      type: array
                      nullable: true
                    storage_configuration:
                      type: object
                      nullable: true
                      properties:
                        sc_dynamic_storage_classname:
                          type: string
                          nullable: true
                        sc_slow_file_storage_classname:
                          type: string
                          nullable: true
                        sc_medium_file_storage_classname:
                          type: string
                          nullable: true
                        sc_fast_file_storage_classname:
                          type: string
                          nullable: true
                    sc_content_initialization:
                      type: boolean
                    sc_content_verification:
                      type: boolean
                    initial_admin_user:
                      type: string
                      nullable: true

                ldap_configuration:
                  type: object
                  description: LDAP Configuration for FNCM
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    lc_selected_ldap_type:
                      type: string
                    lc_ldap_server:
                      type: string
                    lc_ldap_port:
                      type: string
                    lc_bind_secret:
                      type: string
                    lc_ldap_ssl_enabled:
                      type: boolean
                    lc_ldap_ssl_secret_name:
                      type: string
                      nullable: true
                    lc_ldap_base_dn:
                      type: string
                    lc_ldap_user_name_attribute:
                      type: string
                    lc_ldap_user_display_name_attr:
                      type: string
                    lc_ldap_group_base_dn:
                      type: string
                    lc_ldap_group_name_attribute:
                      type: string
                    lc_ldap_group_display_name_attr:
                      type: string
                    lc_ldap_group_membership_search_filter:
                      type: string
                    lc_ldap_group_member_id_map:
                      type: string
                    ad:
                      type: object
                      description: Provide below info if you use Active Directory (ad)
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        lc_ad_gc_host:
                          type: string
                          nullable: true
                        lc_ad_gc_port:
                          type: string
                        lc_user_filter:
                          type: string
                          nullable: true
                        lc_group_filter:
                          type: string
                          nullable: true
                    tds:
                      type: object
                      description: Provide below info if you use Tivoli Directory Service (tds)
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        lc_user_filter:
                          type: string
                          nullable: true
                        lc_group_filter:
                          type: string
                          nullable: true
                    ed:
                      type: object
                      description: Provide below info if you use NetIQ eDirectory (ed)
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        lc_user_filter:
                          type: string
                          nullable: true
                        lc_group_filter:
                          type: string
                          nullable: true
                    oracle:
                      type: object
                      description: Provide below info if you use Oracle (oracle) - OID, OUD and ODSEE
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        lc_user_filter:
                          type: string
                          nullable: true
                        lc_group_filter:
                          type: string
                          nullable: true
                datasource_configuration:
                  type: object
                  description: Datasource Configuration for FNCM
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    dc_ssl_enabled:
                      type: boolean
                    database_precheck:
                      type: boolean
                    dc_gcd_datasource:
                      type: object
                      description: Database configuration for the GCD datasource for CPE
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        dc_database_type:
                          type: string
                        dc_common_gcd_datasource_name:
                          type: string
                        dc_common_gcd_xa_datasource_name:
                          type: string
                        database_servername:
                          type: string
                        database_name:
                          type: string
                        database_port:
                          type: string
                        database_ssl_secret_name:
                          type: string
                          nullable: true
                        dc_oracle_gcd_jdbc_url:
                          type: string
                          nullable: true
                        dc_hadr_standby_servername:
                          type: string
                          nullable: true
                        dc_hadr_standby_port:
                          type: string
                          nullable: true
                        dc_hadr_validation_timeout:
                          type: number
                        dc_hadr_retry_interval_for_client_reroute:
                          type: number
                        dc_hadr_max_retries_for_client_reroute:
                          type: number
                    dc_icn_datasource:
                      type: object
                      description: Database configuration for ICN (Navigator) - aka BAN (Business Automation Navigator)
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        dc_database_type:
                          type: string
                        dc_common_icn_datasource_name:
                          type: string
                        database_servername:
                          type: string
                        database_port:
                          type: string
                        database_name:
                          type: string
                        database_ssl_secret_name:
                          type: string
                          nullable: true
                        dc_oracle_icn_jdbc_url:
                          type: string
                          nullable: true
                        dc_hadr_standby_servername:
                          type: string
                          nullable: true
                        dc_hadr_standby_port:
                          type: string
                          nullable: true
                        dc_hadr_validation_timeout:
                          type: number
                        dc_hadr_retry_interval_for_client_reroute:
                          type: number
                        dc_hadr_max_retries_for_client_reroute:
                          type: number
                initialize_configuration:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    ic_ldap_creation:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        ic_ldap_admin_user_name:
                          items:
                            type: string
                          type: array
                        ic_ldap_admins_groups_name:
                          items:
                            type: string
                          type: array
                    ic_obj_store_creation:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        object_stores:
                          type: array
                          items:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              oc_cpe_obj_store_display_name:
                                type: string
                              oc_cpe_obj_store_symb_name:
                                type: string
                              oc_cpe_obj_store_conn:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                                properties:
                                  dc_os_datasource_name:
                                    type: string
                                  dc_os_xa_datasource_name:
                                    type: string
                              oc_cpe_obj_store_admin_user_groups:
                                items:
                                  type: string
                                type: array
                              oc_cpe_obj_store_enable_workflow:
                                type: boolean
                              oc_cpe_obj_store_workflow_data_tbl_space:
                                type: string
                                nullable: true
                              oc_cpe_obj_store_workflow_admin_group:
                                type: string
                                nullable: true
                              oc_cpe_obj_store_workflow_config_group:
                                type: string
                                nullable: true
                              oc_cpe_obj_store_workflow_pe_conn_point_name:
                                type: string
                                nullable: true
                    ic_icn_init_info:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        icn_repos:
                          type: array
                          items:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              add_repo_id:
                                type: string
                              add_repo_ce_wsi_url:
                                type: string
                              add_repo_os_sym_name:
                                type: string
                              add_repo_os_dis_name:
                                type: string
                              add_repo_workflow_enable:
                                type: boolean
                              add_repo_work_conn_pnt:
                                type: string
                              add_repo_protocol:
                                type: string
                        icn_desktop:
                          type: array
                          items:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              add_desktop_id:
                                type: string
                              add_desktop_name:
                                type: string
                              add_desktop_description:
                                type: string
                              add_desktop_is_default:
                                type: boolean
                              add_desktop_repo_id:
                                type: string
                              add_desktop_repo_workflow_enable:
                                type: boolean
                ecm_configuration:
                  type: object
                  nullable: true
                  x-kubernetes-preserve-unknown-fields: true
            status:
              description: CloudPakAutomationStatus defines the observed state of Automation
              x-kubernetes-preserve-unknown-fields: true
              properties:
                components:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                endpoints:
                  type: array
                  items:
                    properties:
                      type:
                        type: string
                      name:
                        type: string
                      scope:
                        type: string
                      uri:
                        type: string
                      caSecret:
                        type: object
                        properties:
                          secretName:
                            type: string
                          key:
                            type: string
                    type: object
                conditions:
                  items:
                    properties:
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null